---
title: "Layout, themes, HTML (capítulo 6)"
author: "Luis Verde Arregoitia & Virginia García Alonso"
format: 
  revealjs:
    theme: slides.scss
    code-block-height: 600px
editor: 
  mode: source
execute: 
  echo: true
  warning: false
  eval: false
---
## Objetivos de este capítulo

Descubrir herramientas para controlar la apariencia general de la app.

## Hoja de ruta 

1. Diseños de página

2. Cómo personalizar la visualización mediante el uso de "temas"

3. Qué hay "detrás" y cómo modificar aspectos visuales

4. Materiales de interés

## 1. Diseños de página

Explicar a que hace referencia

## 1.1 Diseño de páginas simples

Mostrar la app hello world y el primer layout y darle ‘inspect’ en el navegador
explicar y definir  fluid design y mostrar ejemplos
12 column grid (because the number 12 has more divisors than any number before it or after it, up until the number 60)

## 1.2. Diseño de páginas multiples

anidamiento de tabs
opcion the navlistPanel/navbarPage (modo vertical)



## 2. Temas

no viene en el libro pero mencionar brand_yml que va a ser lo más usado y le pasa los parámetros a bslib *mostrar el diagrama de jerarquía
thematic?
mostrar los themes en bootswatch 


## 3. Que hay detrás: componentes de estilo

- breve mención a que son los componentes de estilo (solo para tener una idea de que son HTML y CSS) y así se entienda que es bootstrap

- Bootstrap es una colección de convenciones HTML, estilos CSS y fragmentos JS agrupados de forma práctica.


- correr un ejemplo sencillo en w3school

## 4. Material de interés

Links y materiales útiles para profundizar y/o ejemplos de donde sacar formatos


